line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "W"]
ignore = [
    "E501",  # line too long
    "E402",  # module level import not at top of file (needed for TF environment variables)
    "F403",  # star imports
    "F405",  # star import names
]
